/*
 * @(#)AuditBean.java
 * $Id$
 */
package nttdm.bsys.a_adt.bean;

import java.io.Serializable;

/**
 * resultClass: id=SELECT.A_ADT.SQL001
 * 
 * @author Generated by TERASOLUNA IDE
 */
public class AuditBean implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 4390979674714255237L;

	/**
	 * id_audit 。
	 */
	private String id_audit = null;

	/**
	 * audit_seq 。
	 */
	private String audit_seq = null;

	/**
	 * id_user 。
	 */
	private String id_user = null;
	
	/**
	 * 
	 */
	private String user_name=null;

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	/**
	 * id_module 。
	 */
	private String id_module = null;

	/**
	 * id_sub_module 。
	 */
	private String id_sub_module = null;

	/**
	 * reference 。
	 */
	private String reference = null;

	/**
	 * table_name 。
	 */
	private String table_name = null;

	/**
	 * at_field 。
	 */
	private String at_field = null;

	/**
	 * old_data 。
	 */
	private String old_data = null;

	/**
	 * new_data 。
	 */
	private String new_data = null;

	/**
	 * action 。
	 */
	private String action = null;
	
	private int index=0;

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	/**
	 * date_created 。
	 */
	private String date_created = null;

	public String getId_audit() {
		return id_audit;
	}

	public void setId_audit(String id_audit) {
		this.id_audit = id_audit;
	}

	public String getAudit_seq() {
		return audit_seq;
	}

	public void setAudit_seq(String audit_seq) {
		this.audit_seq = audit_seq;
	}

	public String getId_user() {
		return id_user;
	}

	public void setId_user(String id_user) {
		this.id_user = id_user;
	}

	public String getId_module() {
		return id_module;
	}

	public void setId_module(String id_module) {
		this.id_module = id_module;
	}

	public String getId_sub_module() {
		return id_sub_module;
	}

	public void setId_sub_module(String id_sub_module) {
		this.id_sub_module = id_sub_module;
	}

	public String getReference() {
		return reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getTable_name() {
		return table_name;
	}

	public void setTable_name(String table_name) {
		this.table_name = table_name;
	}

	public String getAt_field() {
		return at_field;
	}

	public void setAt_field(String at_field) {
		this.at_field = at_field;
	}

	public String getOld_data() {
		return old_data;
	}

	public void setOld_data(String old_data) {
		this.old_data = old_data;
	}

	public String getNew_data() {
		return new_data;
	}

	public void setNew_data(String new_data) {
		this.new_data = new_data;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getDate_created() {
		return date_created;
	}

	public void setDate_created(String date_created) {
		this.date_created = date_created;
	}	

}