/*
 * @(#)M_WLMR01Input.java
 * $Id$
 */
package nttdm.bsys.m_wlm.dto;

import java.io.Serializable;

import nttdm.bsys.common.fw.BillingSystemUserValueObject;

/**
 * parameterClass: id=SELECT.M_WLM.SQL001
 * 
 * @author Generated by TERASOLUNA IDE
 */
public class M_WLMR01Input implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -4695678236515097273L;

	/**
	 * id_screen 
	 */
	private String id_screen = null;
	
	private String id_section_group = null;

	private BillingSystemUserValueObject uvo;
	
	public BillingSystemUserValueObject getUvo() {
		return uvo;
	}

	public void setUvo(BillingSystemUserValueObject uvo) {
		this.uvo = uvo;
	}

	public String getId_section_group() {
		return id_section_group;
	}

	public void setId_section_group(String id_section_group) {
		this.id_section_group = id_section_group;
	}

	public String getId_screen() {
		return this.id_screen;
	}

	public void setId_screen(String id_screen) {
		this.id_screen = id_screen;
	}

}